server:
  port: 8000
spring:
  application:
    name: blog
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    servlet:
      multipart:
        max-request-size: 10MB
        max-file-size: 10MB
  redis:
    host: localhost
    port: 6379
    database: 0
    password: root
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0

logging:
  level:
    com.visitor: debug
  file:
    name: logs/blog.log

netty:
  host: localhost
  port: 8001

